{{- if .Values.rbac.roleBinding.roles -}}
{{- range $role := .Values.rbac.roleBinding.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-{{ $role }}-r
  labels:
{{ include "fiaas-deploy-daemon.labels" $ | indent 4 }}
{{ include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.rbac.roleBinding.labels | indent 4 }}
{{- if or $.Values.annotations.global $.Values.rbac.roleBinding.annotations }}
  annotations:
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.annotations.global | indent 4 }}
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.rbac.roleBinding.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}

{{- if .Values.rbac.roleBinding.clusterRoles -}}
{{- range $clusterRole := .Values.rbac.roleBinding.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-{{ $clusterRole }}-cr
  labels:
{{ include "fiaas-deploy-daemon.labels" $ | indent 4 }}
{{ include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.rbac.roleBinding.labels | indent 4 }}
{{- if or $.Values.annotations.global $.Values.rbac.roleBinding.annotations }}
  annotations:
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.annotations.global | indent 4 }}
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" $.Values.rbac.roleBinding.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
