{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "fiaas-deploy-daemon.labels" . | indent 4 }}
{{ include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.rbac.serviceAccount.labels | indent 4 }}
{{- if or .Values.annotations.global .Values.rbac.serviceAccount.annotations }}
  annotations:
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.annotations.global | indent 4 }}
{{- include "fiaas-deploy-daemon.labelsOrAnnotations" .Values.rbac.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end -}}
